const dbProducts = [
  {
    image: "Images/passiveRentalIncome.png",
    title: "Passive Income from Real Estate (₹1 Lakh/month) 5% Per annum",
    rating: 5,
    flipkartAssured: false,
    price: 34500000,
    deliveryIn1Day: false,
    noCostEMI: false,
    specialPrice: 24500000,
    discountPrice: 28.99,
    popularity: 90,
  },
  {
      image: "Images/mmtcGold.png",
      title: "MMTC PAMP 999.9 Pure Gold (1Kg)",
      rating: 3,
      flipkartAssured: true,
      price: 9000000,
      deliveryIn1Day: true,
      noCostEMI: true,
      specialPrice: 7000000,
      discountInPercentage: 22.22,
      popularity: 70,
  },
  {
      image: "Images/mmtcSilver.png",
      title: "MMTC PAMP 999.9 Pure Silver (1Kg)",
      rating: 3,
      flipkartAssured: true,
      price: 120000,
      deliveryIn1Day: true,
      noCostEMI: true,
      specialPrice: 100000,
      discountInPercentage: 16.67,
      popularity: 60,
  },
  {
      image: "Images/100BighaLandInPorscheArea.png",
      title: "Land in Posh Area (1 Bigha)",
      rating: 3,
      flipkartAssured: true,
      price: 40000000,
      deliveryIn1Day: false,
      noCostEMI: false,
      specialPrice: 30000000,
      discountInPercentage: 25,
      popularity: 70,
  },
  {
      image: "Images/100BighaOrchard.png",
      title: "Orchard Fruits, Herbs, Vegetable (10 Bigha)",
      rating: 5,
      flipkartAssured: true,
      price: 500000000,
      deliveryIn1Day: false,
      noCostEMI: false,
      specialPrice: 300000000,
      discountInPercentage: 40,
      popularity: 70,
  },
  {
      image: "Images/EmergencyFund.png",
      title: "Emergency Fund LiquidBees (₹ 1 Lakh)",
      rating: 5,
      flipkartAssured: true,
      price: 100000,
      deliveryIn1Day: false,
      noCostEMI: false,
      specialPrice: null,
      discountInPercentage: null,
      popularity: 100,
  },
  {
      image: "Images/wholeFamilyHealthInsurance.png",
      title: "Whole Family Health Insurance (₹ 2 Lakh)",
      rating: 5,
      flipkartAssured: true,
      price: 700000,
      deliveryIn1Day: true,
      noCostEMI: true,
      specialPrice: 200000,
      discountInPercentage: 71.43,
      popularity: 100,
  },

  {
      image: "Images/stockMarketDividendIncome.png",
      title: "Passive income from stock market ₹1 Lakh/month (Covered Call || Dividends) 12% per annnum",
      rating: 5,
      flipkartAssured: true,
      price: 2000000,
      deliveryIn1Day: true,
      noCostEMI: false,
      specialPrice: 1000000,
      discountPrice: 50,
      popularity: 100,
  },
  {
      image: "Images/TradingSetup.png",
      title: "Trading Setup (1. Dell Alienware Area 51 M R2 Laptop, 2. Two Samsung Odysey G9 49 inches Curved Monitors)",
      rating: 5,
      flipkartAssured: true,
      price: 900000,
      deliveryIn1Day: true,
      noCostEMI: true,
      specialPrice: 700000,
      discountPrice: 22.22,
      popularity: 100,
  },
  {
      image: "Images/harleyDavidson48.png",
      title: "Harley Davidson Forty Eight",
      rating: 2,
      flipkartAssured: false,
      price: 1200000,
      deliveryIn1Day: true,
      noCostEMI: null,
      specialPrice: null,
      discountPrice: null,
      popularity: 50,
  },
  {
      image: "Images/toyotaFortuner.png",
      title: "Toyota Fortuner",
      rating: 2,
      flipkartAssured: false,
      price: 5300000,
      deliveryIn1Day: true,
      noCostEMI: true,
      specialPrice: null,
      discountPrice: null,
      popularity: 30,
  },
  {
      image: "Images/porsche911Carrera4GTS.png",
      title: "Porsche 911 Carrera 4 GTS",
      rating: 3,
      flipkartAssured: false,
      price: 40000000,
      deliveryIn1Day: false,
      noCostEMI: true,
      specialPrice: null,
      discountPrice: null,
      popularity: 80,
  },
  {
      image: "Images/worldTour.png",
      title: "World Tour",
      rating: 5,
      flipkartAssured: true,
      price: 5000000,
      deliveryIn1Day: false,
      noCostEMI: true,
      specialPrice: null,
      discountPrice: null,
      popularity: 100,
  },
  {
      image: "Images/privateLimitedCompaniesSetup.png",
      title: "Private Limited Companies Set Up (Financial Education, Rental Real Estate, Franchise Businesses)",
      rating: 5,
      flipkartAssured: true,
      price: 750000000,
      deliveryIn1Day: false,
      noCostEMI: true,
      specialPrice: null,
      discountPrice: null,
      popularity: 100,
  },




  // {
  //     image: "product2.png",
  //     title: "Product 2",
  //     rating: 4.2,
  //     flipkartAssured: false,
  //     price: 299.99,
  //     deliveryIn1Day: false,
  //     noCostEMI: true,
  //     specialPrice: 279.99,
  //     discountPrice: 20.00,
  //     popularity: 100,
  // },
  // {
  //     image: "product3.png",
  //     title: "Product 3",
  //     rating: 3.9,
  //     flipkartAssured: true,
  //     price: 699.99,
  //     deliveryIn1Day: true,
  //     noCostEMI: false,
  //     specialPrice: 599.99,
  //     discountPrice: 100.00,
  //     popularity: 500,
  // },
  // {
  //     image: "product4.png",
  //     title: "Product 4",
  //     rating: 4.7,
  //     flipkartAssured: true,
  //     price: 199.99,
  //     deliveryIn1Day: false,
  //     noCostEMI: true,
  //     specialPrice: 179.99,
  //     discountPrice: 20.00,
  //     popularity: 900,
  // },
  // {
  //     image: "product5.png",
  //     title: "Product 5",
  //     rating: 4.3,
  //     flipkartAssured: true,
  //     price: 899.99,
  //     deliveryIn1Day: true,
  //     noCostEMI: true,
  //     specialPrice: 849.99,
  //     discountPrice: 50.00,
  //     popularity: 10,
  // },
  // {
  //     image: "product6.png",
  //     title: "Product 6",
  //     rating: 4.0,
  //     flipkartAssured: false,
  //     price: 399.99,
  //     deliveryIn1Day: true,
  //     noCostEMI: false,
  //     specialPrice: 359.99,
  //     discountPrice: 40.00,
  //     popularity: 50,
  // },
  // {
  //     image: "product7.png",
  //     title: "Product 7",
  //     rating: 4.8,
  //     flipkartAssured: true,
  //     price: 599.99,
  //     deliveryIn1Day: true,
  //     noCostEMI: true,
  //     specialPrice: 549.99,
  //     discountPrice: 50.00,
  //     popularity: 1000,
  // },
  // {
  //     image: "product8.png",
  //     title: "Product 8",
  //     rating: 4.1,
  //     flipkartAssured: true,
  //     price: 349.99,
  //     deliveryIn1Day: false,
  //     noCostEMI: false,
  //     specialPrice: 329.99,
  //     discountPrice: 20.00,
  //     popularity: 2,
  // },
  // {
  //     image: "product9.png",
  //     title: "Product 9",
  //     rating: 3.8,
  //     flipkartAssured: true,
  //     price: 799.99,
  //     deliveryIn1Day: true,
  //     noCostEMI: true,
  //     specialPrice: 749.99,
  //     discountPrice: 50.00,
  //     popularity: 34634,
  // },
  // {
  //     image: "product10.png",
  //     title: "Product 10",
  //     rating: 4.6,
  //     flipkartAssured: false,
  //     price: 249.99,
  //     deliveryIn1Day: false,
  //     noCostEMI: true,
  //     specialPrice: 229.99,
  //     discountPrice: 20.00,
  //     popularity: 9800,
  // },
  // {
  //     image: "product11.png",
  //     title: "Product 11",
  //     rating: 4.4,
  //     flipkartAssured: true,
  //     price: 599.99,
  //     deliveryIn1Day: true,
  //     noCostEMI: false,
  //     specialPrice: 579.99,
  //     discountPrice: 20.00,
  //     popularity: 201,
  // },
  // {
  //     image: "product12.png",
  //     title: "Product 12",
  //     rating: 4.9,
  //     flipkartAssured: true,
  //     price: 179.99,
  //     deliveryIn1Day: false,
  //     noCostEMI: true,
  //     specialPrice: 169.99,
  //     discountPrice: 10.00,
  //     popularity: 199,
  // },
  // {
  //     image: "product13.png",
  //     title: "Product 13",
  //     rating: 4.2,
  //     flipkartAssured: true,
  //     price: 899.99,
  //     deliveryIn1Day: true,
  //     noCostEMI: true,
  //     specialPrice: 849.99,
  //     discountPrice: 50.00,
  //     popularity: 2300,
  // },
  // {
  //     image: "product14.png",
  //     title: "Product 14",
  //     rating: 4.3,
  //     flipkartAssured: false,
  //     price: 449.99,
  //     deliveryIn1Day: true,
  //     noCostEMI: false,
  //     specialPrice: 429.99,
  //     discountPrice: 20.00,
  //     popularity: 990,
  // },
  // {
  //     image: "product15.png",
  //     title: "Product 14",
  //     rating: 4.3,
  //     flipkartAssured: false,
  //     price: 449.99,
  //     deliveryIn1Day: true,
  //     noCostEMI: false,
  //     specialPrice: 429.99,
  //     discountPrice: 20.00,
  //     popularity: 990,
  // },
  
];